-- Script generado dinámicamente para insertar Categorías, Subcategorías y Productos

-- Categoría Aceites
INSERT INTO categorias (id_categoria, nombre_categoria) VALUES (1, 'Aceites') ON CONFLICT (nombre_categoria) DO NOTHING;

-- Subcategoría: De Motor
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (1, 'De Motor');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite de Motor Sintético GTX 5W-30', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Motor'), 'Castrol', 'Aceite 100% sintético para máxima protección del motor en ciudad y carretera.', 'Viscosidad: 5W-30 | Tipo: 100% Sintético | Presentación: 4 Litros | API SN Plus', '/uploads/aceites_demotor_1.webp', 280.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite de Motor Semi-Sintético 10W-40 4100', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Motor'), 'Motul', 'Formulación avanzada para motores a gasolina y diésel de alto rendimiento.', 'Viscosidad: 10W-40 | Tipo: Semi-Sintético | Presentación: 4 Litros | API SN/CF', '/uploads/aceites_demotor_2.webp', 320.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite de Motor Alto Kilometraje 20W-50', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Motor'), 'Valvoline', 'Diseñado con aditivos acondicionadores para motores con más de 100,000 km.', 'Viscosidad: 20W-50 | Tipo: Mineral | Presentación: 4 Litros | Recomendado +100,000 km', '/uploads/aceites_demotor_3.webp', 210.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite de Motor Mineral 15W-40 GT-1', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Motor'), 'Valvoline', 'Excelente protección contra la fricción y desgaste a temperaturas extremas.', 'Viscosidad: 15W-40 | Tipo: Mineral | Presentación: 4 Litros | API SN', '/uploads/aceites_demotor_4.webp', 185.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite de Motor Sintético 8100 X-cess 5W-40', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Motor'), 'Motul', 'Lubricante de alta gama diseñado para vehículos modernos de gran potencia.', 'Viscosidad: 5W-40 | Tipo: 100% Sintético | Presentación: 4 Litros | ACEA C3', '/uploads/aceites_demotor_5.webp', 395.00, 25);

-- Subcategoría: De Transmisión
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (1, 'De Transmisión');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite para Transmisión Automática ATF Dexron VI', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Transmisión'), 'Valvoline', 'Fluido sintético de baja viscosidad para transmisiones automáticas modernas.', 'Tipo: ATF Dexron VI | Presentación: 1 Litro | Uso: Transmisión Automática', '/uploads/aceites_detransmisión_6.webp', 95.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite para Transmisión Manual 75W-90 Motylgear', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Transmisión'), 'Motul', 'Especialmente formulado para cajas de cambios de difícil transmisión.', 'Viscosidad: 75W-90 | Tipo: Sintético | Presentación: 1 Litro | API GL-4/GL-5', '/uploads/aceites_detransmisión_7.webp', 130.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite para Transmisión CVT Fluid', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Transmisión'), 'Castrol', 'Fluido de rendimiento superior para transmisiones continuamente variables.', 'Tipo: CVT Fluid | Presentación: 1 Litro | Uso: Transmisión CVT', '/uploads/aceites_detransmisión_8.webp', 115.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite para Transmisión Automática Transmax Multi-Vehicle', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Transmisión'), 'Castrol', 'Ofrece una suave transición de marchas y excelente durabilidad térmica.', 'Tipo: ATF Multi-Vehicle | Presentación: 1 Litro | Uso: Transmisión Automática', '/uploads/aceites_detransmisión_9.webp', 85.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aceite para Diferenciales y Cajas Hypoid 80W-90', 1, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 1 AND nombre_subcategoria = 'De Transmisión'), 'Liqui Moly', 'Lubricante para transmisiones mecánicas y ejes con cargas elevadas.', 'Viscosidad: 80W-90 | Tipo: Hypoid | Presentación: 1 Litro | API GL-5', '/uploads/aceites_detransmisión_10.webp', 120.00, 25);



-- Categoría Filtros
INSERT INTO categorias (id_categoria, nombre_categoria) VALUES (2, 'Filtros') ON CONFLICT (nombre_categoria) DO NOTHING;

-- Subcategoría: De Aire
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (2, 'De Aire');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aire de Alto Flujo', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aire'), 'WIX', 'Retiene el 99% de los contaminantes asegurando óptimo flujo de aire al motor.', 'Material: Algodón de alto flujo | Eficiencia: 99% | Lavable/Reutilizable', '/uploads/filtros_deaire_11.webp', 110.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aire Estándar Panel', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aire'), 'Mann-Filter', 'Filtración eficiente para proteger contra polvo, polen y partículas finas.', 'Material: Papel plisado | Tipo: Panel | Uso: Reemplazo OEM', '/uploads/filtros_deaire_12.webp', 95.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aire Cilíndrico Heavy Duty', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aire'), 'Bosch', 'Diseñado para resistir condiciones severas de polvo y trayectos largos.', 'Material: Papel reforzado | Tipo: Cilíndrico | Uso: Heavy Duty', '/uploads/filtros_deaire_13.webp', 145.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aire de Cabina / Polen', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aire'), 'Mann-Filter', 'Protege el habitáculo reteniendo alérgenos e impurezas del medio ambiente.', 'Material: Carbón activado | Tipo: Cabina/Polen | Retiene alérgenos y olores', '/uploads/filtros_deaire_14.webp', 125.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aire Deportivo Reemplazo', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aire'), 'WIX', 'Maximiza la potencia y respuesta de aceleración del vehículo.', 'Material: Algodón deportivo | Tipo: Alto rendimiento | Reutilizable', '/uploads/filtros_deaire_15.webp', 160.00, 25);

-- Subcategoría: De Aceite
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (2, 'De Aceite');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aceite de Gran Capacidad', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aceite'), 'WIX', 'Construcción reforzada con alta capacidad de retención de impurezas.', 'Tipo: Spin-On | Capacidad: Alta | Rosca estándar 3/4-16', '/uploads/filtros_deaceite_16.webp', 65.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aceite Sintético Blindado', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aceite'), 'Bosch', 'Válvula anti-retorno y elemento filtrante apto para sintéticos.', 'Tipo: Spin-On | Elemento: Sintético | Válvula anti-retorno incluida', '/uploads/filtros_deaceite_17.webp', 85.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aceite Elemento de Papel', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aceite'), 'Mann-Filter', 'Reemplazo ecológico con máxima eficiencia de filtración.', 'Tipo: Elemento de Papel | Eficiencia: Alta | Uso: Reemplazo OEM', '/uploads/filtros_deaceite_18.webp', 70.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aceite de Rendimiento Estándar', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aceite'), 'Bosch', 'Diseñado para intervalos regulares de cambio de aceite mineral o sintético.', 'Tipo: Spin-On | Uso: Aceite mineral/sintético | Rosca estándar', '/uploads/filtros_deaceite_19.webp', 55.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Filtro de Aceite Spin-On Reforzado', 2, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 2 AND nombre_subcategoria = 'De Aceite'), 'WIX', 'Carcasa resistente a picos de presión dentro del sistema de lubricación.', 'Tipo: Spin-On Reforzado | Presión máx: Alta | Carcasa metálica', '/uploads/filtros_deaceite_20.webp', 75.00, 25);



-- Categoría Aditivos
INSERT INTO categorias (id_categoria, nombre_categoria) VALUES (3, 'Aditivos') ON CONFLICT (nombre_categoria) DO NOTHING;

-- Subcategoría: Anticongelantes
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (3, 'Anticongelantes');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Refrigerante / Anticongelante Listo para Usar 50/50', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Anticongelantes'), 'Prestone', 'Fórmula multimarca que protege contra la corrosión y el sobrecalentamiento.', 'Dilución: 50/50 Lista para usar | Presentación: 1 Galón | Multimarca', '/uploads/aditivos_anticongelantes_21.webp', 135.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Refrigerante Anticongelante Concentrado 100%', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Anticongelantes'), 'Prestone', 'Requiere dilución; provee protección extrema contra congelación y ebullición.', 'Concentración: 100% (requiere dilución) | Presentación: 1 Galón', '/uploads/aditivos_anticongelantes_22.webp', 175.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Anticongelante Orgánico OAT Rojo', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Anticongelantes'), 'Liqui Moly', 'Libre de nitritos, aminas y fosfatos, especial para motores de aluminio.', 'Tecnología: OAT | Color: Rojo | Presentación: 1 Litro | Apto motores de aluminio', '/uploads/aditivos_anticongelantes_23.webp', 160.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aditivo Tratamiento para Radiador Super Coolant', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Anticongelantes'), 'STP', 'Mejora la transferencia de calor y reduce la temperatura del sistema.', 'Presentación: 325 ml | Uso: Aditivo para sistema de enfriamiento', '/uploads/aditivos_anticongelantes_24.webp', 65.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Refrigerante / Anticongelante Universal Verde', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Anticongelantes'), 'Prestone', 'Protección estándar para sistemas de enfriamiento convencionales.', 'Tecnología: IAT | Color: Verde | Presentación: 1 Galón', '/uploads/aditivos_anticongelantes_25.webp', 110.00, 25);

-- Subcategoría: Limpiadores de Inyectores
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (3, 'Limpiadores de Inyectores');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Limpiador de Inyectores de Alto Rendimiento Injection Reiniger', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Limpiadores de Inyectores'), 'Liqui Moly', 'Remueve depósitos en válvulas e inyectores, restaurando la potencia.', 'Presentación: 300 ml | Uso: Motores a gasolina | Rinde para 1 tanque', '/uploads/aditivos_limpiadoresdeinyectores_26.webp', 115.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Tratamiento Limpiador de Inyectores Gasolina', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Limpiadores de Inyectores'), 'STP', 'Fórmula concentrada para eliminar residuos de carbón en un solo tanque.', 'Presentación: 155 ml | Uso: Motores a gasolina | Un solo tanque', '/uploads/aditivos_limpiadoresdeinyectores_27.webp', 55.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Limpiador de Inyectores Diesel System Cleaner', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Limpiadores de Inyectores'), 'Liqui Moly', 'Protege el sistema de inyección diésel contra la corrosión y el desgaste.', 'Presentación: 500 ml | Uso: Motores diésel | Protección anticorrosión', '/uploads/aditivos_limpiadoresdeinyectores_28.webp', 125.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Limpiador Completo del Sistema de Combustible', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Limpiadores de Inyectores'), 'STP', 'Limpia inyectores, carburadores, válvulas de admisión y cámaras de combustión.', 'Presentación: 325 ml | Uso: Sistema completo de combustible', '/uploads/aditivos_limpiadoresdeinyectores_29.webp', 85.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Aditivo Estabilizador y Limpiador de Combustible', 3, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 3 AND nombre_subcategoria = 'Limpiadores de Inyectores'), 'STP', 'Previene la degradación del combustible y mantiene limpios los inyectores.', 'Presentación: 325 ml | Uso: Estabilizador para almacenamiento prolongado', '/uploads/aditivos_limpiadoresdeinyectores_30.webp', 70.00, 25);



-- Categoría Repuestos
INSERT INTO categorias (id_categoria, nombre_categoria) VALUES (4, 'Repuestos') ON CONFLICT (nombre_categoria) DO NOTHING;

-- Subcategoría: Freno
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (4, 'Freno');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Pastillas de Freno Cerámicas Delanteras', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Freno'), 'Brembo', 'frenado silencioso, bajo nivel de polvo y excelente durabilidad.', 'Material: Cerámico | Posición: Delantera | Presentación: Juego (4 pzs)', '/uploads/repuestos_freno_31.webp', 380.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Discos de Freno Ventilados (Par)', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Freno'), 'Brembo', 'Discos con recubrimiento anticorrosivo y disipación térmica optimizada.', 'Tipo: Ventilado | Recubrimiento: Anticorrosivo | Presentación: Par (2 pzs)', '/uploads/repuestos_freno_32.webp', 750.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Pastillas de Freno Semimetálicas', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Freno'), 'Bosch', 'Respuesta inmediata de frenado en condiciones de alta carga o temperatura.', 'Material: Semimetálico | Presentación: Juego (4 pzs)', '/uploads/repuestos_freno_33.webp', 290.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Líquido de Frenos DOT 4 Synthetic', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Freno'), 'Brembo', 'Punto de ebullición elevado para prevenir el desfallecimiento de frenos.', 'Especificación: DOT 4 Sintético | Presentación: 500 ml', '/uploads/repuestos_freno_34.webp', 75.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Zapatas de Freno Traseras', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Freno'), 'Bosch', 'Fricción constante para sistemas de freno de tambor traseros.', 'Material: Fricción orgánica | Posición: Trasera | Presentación: Juego (4 pzs)', '/uploads/repuestos_freno_35.webp', 230.00, 25);

-- Subcategoría: Transmisión Manual
INSERT INTO subcategorias (id_categoria, nombre_subcategoria) VALUES (4, 'Transmisión Manual');
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Kit de Embrague Completo (Disco, Canasta y Collarín)', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Transmisión Manual'), 'Bosch', 'Repuesto de alta resistencia para un acople suave y eficiente.', 'Incluye: Disco, Canasta y Collarín | Uso: Transmisión Manual', '/uploads/repuestos_transmisiónmanual_36.webp', 1250.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Cilindro Maestro de Embrague', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Transmisión Manual'), 'Bosch', 'Componente hidráulico de precisión para la activación del embrague.', 'Tipo: Cilindro Maestro | Sistema: Hidráulico', '/uploads/repuestos_transmisiónmanual_37.webp', 340.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Cilindro Esclavo de Embrague', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Transmisión Manual'), 'Bosch', 'Cilindro receptor resistente a fluidos hidráulicos de alta presión.', 'Tipo: Cilindro Esclavo | Sistema: Hidráulico', '/uploads/repuestos_transmisiónmanual_38.webp', 260.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Cojinete de Empuje / Collarín de Embrague', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Transmisión Manual'), 'Bosch', 'Rodamiento de alta durabilidad para la liberación del embrague.', 'Tipo: Cojinete de empuje | Uso: Liberación de embrague', '/uploads/repuestos_transmisiónmanual_39.webp', 180.00, 25);
INSERT INTO productos (nombreproducto, id_categoria, id_subcategoria, marca, descripcion, especificaciones, imagen_principal, precioproducto, stock) VALUES ('Cable de Selector de Marchas', 4, (SELECT id_subcategoria FROM subcategorias WHERE id_categoria = 4 AND nombre_subcategoria = 'Transmisión Manual'), 'Bosch', 'Sustituto de alta precisión para el varillaje de cambios de caja manual.', 'Tipo: Cable de selector | Uso: Caja manual', '/uploads/repuestos_transmisiónmanual_40.webp', 210.00, 25);



SELECT setval('categorias_id_categoria_seq', (SELECT MAX(id_categoria) FROM categorias));
SELECT setval('subcategorias_id_subcategoria_seq', (SELECT MAX(id_subcategoria) FROM subcategorias));
SELECT setval('productos_idproducto_seq', (SELECT MAX(idproducto) FROM productos));